// This file is a server component. Do not use client-only context providers here.
// Use context providers in client layouts or pages instead.
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
// import { ReactScan } from "@/components/ReactScan";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Wedevent Focalat',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png', // Path relative to the public folder
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ReactScan /> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}>
        {/* QuoteProvider must be used in a client layout or page, not here */}
        {children}
      </body>
    </html>
  );
}
